"""Single source of truth for the project's current headline numbers (§2, §39).

The problem this solves: headline counts (episode counts, test counts, coverage %, ESDI)
were being hand-copied into several docs and drifting out of sync. Instead of policing prose,
the build regenerates ONE file — docs/CURRENT_STATE.md — from the snapshot, and a test asserts
it is not stale. Narrative docs point here rather than re-quoting numbers that go stale.

render() is pure (snapshot + test_count -> markdown) so the test can regenerate and compare.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs" / "CURRENT_STATE.md"
TEST_FILE = ROOT / "tests" / "test_pipeline.py"


def count_tests(test_file=TEST_FILE):
    try:
        src = test_file.read_text(encoding="utf-8")
    except OSError:
        return 0
    return len(re.findall(r"^def (test_\w+)", src, re.MULTILINE))


def render(snapshot, test_count):
    """Deterministic markdown for the current headline numbers. Pure function."""
    s = snapshot
    rs = s.get("recovery_stats", {})
    cov = s.get("coverage") or {}
    rr = s.get("refinery_reconciliation") or {}
    cl = rr.get("canonical_linkage") or {}
    gas = ((s.get("experimental_indices") or {}).get("gas_processing")) or {}
    tx = s.get("transmission_sensitivity") or {}
    se = s.get("strategic_effects") or {"national": [], "by_incident": {}}
    sectors = s.get("sectors", {})
    sweep = tx.get("saturation_sweep") or []
    sweep_lo = min((r["sector_value"] for r in sweep), default=None)
    sweep_hi = max((r["sector_value"] for r in sweep), default=None)

    def f(x, n=2):
        return "—" if x is None else f"{x:.{n}f}"

    lines = [
        "# Current state — generated, do not hand-edit",
        "",
        "> Regenerated by `python -m pipeline.run` from `data/processed/snapshot.json`.",
        "> A test (`test_current_state_doc_is_in_sync`) fails if this drifts from the build.",
        "> Other docs should link here instead of re-quoting these numbers (§2).",
        "",
        f"- **as_of**: {s.get('as_of')}",
        f"- **Headline ESDI (monitored area)**: {f(s.get('esdi'))}",
        f"- **Uncovered-sector zero-assumption sensitivity**: "
        f"{f(s.get('uncovered_zero_assumption_sensitivity', s.get('esdi_all_sectors')))}",
        "- **Sector exposures**: "
        + ", ".join(f"{k} {f(v)}" for k, v in sectors.items()),
        "",
        "## Coverage",
        f"- **Oil-strike benchmark coverage**: {f((cov.get('coverage_ratio') or 0) * 100, 1)}% "
        f"({cov.get('enumerated_in_this_dataset')} enumerated oil-sector strikes / "
        f"{cov.get('reported_total_strikes')} reported)",
        f"- **Total events across all sectors**: {cov.get('total_events_all_sectors')}",
        "",
        "## Recovery",
        f"- **Observed-restoration episodes (monitored area)**: n = {rs.get('observed_restoration_episodes')}",
        f"- **Recovery records / partial / full / estimate**: "
        f"{rs.get('recovery_record_count')} / {rs.get('partial_restart_episodes')} / "
        f"{rs.get('full_reconstitution_episodes')} / {rs.get('estimate_episodes')}",
        f"- **Per-class medians (n ≥ {rs.get('min_sector_median_episodes')})**: "
        + (", ".join(f"{k} {v}d" for k, v in (rs.get('sector_medians') or {}).items()) or "none yet"),
        f"- **Pooled cross-class median (mixed-infrastructure, not headline)**: "
        f"{rs.get('median_observed_restoration_days')}",
        "",
        "## Refining denominator",
        f"- **Tracked refining base**: {f(rr.get('tracked_mtpa'), 1)} MTPA across "
        f"{rr.get('tracked_refineries')} denominator refineries",
        f"- **Canonical linkage (identity, NOT disruption coverage)**: "
        f"{cl.get('struck_refineries')}/{cl.get('denominator_refineries')} refineries struck = "
        f"{cl.get('pct_denominator_mtpa_struck')}% of denominator MTPA",
        "",
        "## Gas processing (experimental, NOT in headline ESDI)",
        f"- **Within-census exposure**: {f(gas.get('within_census_exposure_pct'), 1)}% "
        f"({gas.get('struck_plants')} of {gas.get('census_plants')} censused plants, "
        f"{f(gas.get('census_bcm_y'), 2)} bcm/y total)",
        "",
        "## Transmission (event-burden, theatre-concentrated)",
        f"- **Headline value**: {f(sectors.get('transmission'))} at saturation "
        f"{tx.get('saturation_constant')}",
        f"- **Sensitivity range across saturations**: {f(sweep_lo)}–{f(sweep_hi)}",
        f"- **Top-theatre share**: {f(tx.get('top_region_share_pct'), 1)}% over "
        f"{tx.get('distinct_affected_regions')} region(s)",
        "",
        "## Strategic effects (source-backed, observational)",
        f"- **National/macro datapoints**: {len(se.get('national', []))}",
        f"- **Per-incident effects**: {sum(len(v) for v in se.get('by_incident', {}).values())} "
        f"across {len(se.get('by_incident', {}))} incidents",
        "",
        "## Tests",
        f"- **Python test functions** (`tests/test_pipeline.py`): {test_count} "
        "(pytest reports more cases — some functions are parametrized)",
        "",
    ]
    return "\n".join(lines)


def write(snapshot, path=DOC):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(snapshot, count_tests()), encoding="utf-8")
    return path


def _main():
    snap = json.loads((ROOT / "data" / "processed" / "snapshot.json").read_text(encoding="utf-8"))
    p = write(snap)
    print(f"wrote {p}")


if __name__ == "__main__":
    _main()
