"""Build everything. `python -m pipeline.run`

Order matters: regions before assets (assets need the point-in-region index),
sources before the index, index before the web payload.

Output lands in data/processed/ and is mirrored into web/public/data/ so the Vite
build can serve it as static files. The database-shaped middle layer that a bigger
system would have is deliberately absent -- at this size, static JSON regenerated by
a scheduled job is the whole backend.
"""

import argparse
import datetime as dt
import shutil

from pipeline import build_assets, build_context, build_index
from pipeline.config import (
    ANALYTIC_CONCEPTS, ASSET_CLASSES, CURATED, DISRUPTION_CAUSES, EVIDENCE_KINDS,
    PROCESSED, SECTORS, WEB_DATA, WINDOW_START,
)
from pipeline.fetch_refineries import build as build_refineries
from pipeline.fetch_wikipedia import build as build_wikipedia
from pipeline.recovery import load_recovery_records
from pipeline.util import fetch_json, log, read_csv, write_json

COVERAGE_PAGE = "2025%E2%80%932026_Russian_fuel_crisis"
COVERAGE_URL = "https://en.wikipedia.org/wiki/2025%E2%80%932026_Russian_fuel_crisis"


def load_curated_incidents():
    """Read the analyst-maintained incident file.

    This is the extension point for anything the automated parsers cannot reach:
    non-kinetic causes, electricity and gas events, and anything reported only in
    prose. Every row must carry at least one source URL.
    """
    path = CURATED / "incidents.csv"
    if not path.exists():
        return []
    out = []
    for row in read_csv(path):
        urls = [u for u in (row.get("source_urls") or "").split("|") if u]
        types = [t for t in (row.get("source_types") or "").split("|") if t]
        if not urls:
            log(f"  WARN curated incident {row.get('incident_id')} has no source URL; skipped")
            continue
        out.append(
            {
                "incident_id": row["incident_id"],
                "asset_id": row.get("asset_id") or row["incident_id"],
                "asset_name": row.get("asset_name"),
                "linked_asset_id": row.get("linked_asset_id"),
                "asset_class": row.get("asset_class"),
                "region_code": row.get("region_code"),
                "date": row["date"],
                "date_end": row.get("date_end"),
                "date_precision": row.get("date_precision") or "day",
                "cause": row.get("cause") or "unknown",
                "attribution": row.get("attribution") or "none",
                "attribution_confidence": row.get("attribution_confidence") or "not_applicable",
                "status": row.get("status") or "unknown",
                "confidence": row.get("confidence") or "possible",
                "capacity_affected_mw": _num(row.get("capacity_affected_mw")),
                "capacity_affected_mtpa": _num(row.get("capacity_affected_mtpa")),
                "capacity_affected_pct": _num(row.get("capacity_affected_pct")),
                # Cost / economic scaffolding (iteration 1). Null unless a source gives a
                # figure. reported = a source stated it; estimated = an external estimate;
                # never a value the pipeline invents.
                "repair_cost_reported_usd_m": _num(row.get("repair_cost_reported_usd_m")),
                "repair_cost_estimate_low_usd_m": _num(row.get("repair_cost_estimate_low_usd_m")),
                "repair_cost_estimate_high_usd_m": _num(row.get("repair_cost_estimate_high_usd_m")),
                "cost_basis": row.get("cost_basis"),
                "conflicting_reports": (row.get("conflicting_reports") or "").lower() == "true",
                "notes": row.get("notes"),
                "first_seen": row.get("first_seen"),
                "last_verified": row.get("last_verified"),
                "sources": [
                    {"url": u, "publisher": None, "title": None,
                     "source_type": types[i] if i < len(types) else None}
                    for i, u in enumerate(urls)
                ],
                "origin": "curated",
            }
        )
    log(f"curated: {len(out)} incidents")
    return out


def _num(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def load_coverage_benchmark():
    """Reported strike totals by war year, used to state our own coverage honestly.

    The source article tabulates how many strikes on Russian oil facilities have been
    reported in total. Comparing that with the number this dataset actually enumerates
    is the most useful single honesty statistic the dashboard can show.
    """
    from pipeline import wikitext as W

    url = (
        "https://en.wikipedia.org/w/api.php?action=parse&page="
        f"{COVERAGE_PAGE}&prop=wikitext&format=json&formatversion=2"
    )
    try:
        wt = fetch_json(url, "wiki_fuel_crisis.json", max_age_hours=24)["parse"]["wikitext"]
    except Exception as exc:  # noqa: BLE001 - benchmark is optional context
        log(f"  WARN coverage benchmark unavailable: {exc}")
        return None

    for table in W.find_tables(wt):
        headers, rows, spans = W.parse_table(table)
        head = [W.clean_cell(h).lower() for h in headers]
        if "cumulative" not in head:
            continue
        periods = []
        cumulative = None
        for row in rows:
            cells = [W.clean_cell(W.restore(c, spans)) for c in row]
            if len(cells) < 3:
                continue
            try:
                in_year = int(cells[-2].replace(",", ""))
                cum = int(cells[-1].replace(",", ""))
            except ValueError:
                continue
            periods.append({"period": cells[0], "strikes": in_year, "cumulative": cum})
            cumulative = cum
        if periods:
            return {
                "reported_total_strikes": cumulative,
                "by_period": periods,
                "source_url": COVERAGE_URL,
                "note": (
                    "Reported strikes on Russian oil facilities, as tabulated by the "
                    "source article. Used only to state this dataset's coverage; not "
                    "an input to any score."
                ),
            }
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--as-of", default=dt.date.today().isoformat())
    args = ap.parse_args()

    log("=" * 62)
    log(f"build starting, as_of={args.as_of}")
    log("=" * 62)

    assets, lines, region_meta = build_assets.build()
    build_context.build()  # surrounding countries, borders, ocean — display only
    wiki_facilities, wiki_incidents, wiki_warnings = build_wikipedia()
    refineries, refining_total = build_refineries()
    curated = load_curated_incidents()
    coverage = load_coverage_benchmark()
    recovery_by_incident = load_recovery_records()

    for inc in wiki_incidents:
        inc["origin"] = "wikipedia_strike_table"
        inc.setdefault("status", "unknown")

    incidents = wiki_incidents + curated
    incidents = [i for i in incidents if i["date"] >= WINDOW_START[:len(i["date"])]]
    incidents.sort(key=lambda i: i["date"])

    # Attach federal district to each region-assigned incident, for coverage analytics.
    district_of = {m["code"]: m["district"] for m in region_meta.values()}
    for inc in incidents:
        if inc.get("region_code"):
            inc["_district"] = district_of.get(inc["region_code"])

    in_aoi = [i for i in incidents if i.get("region_code")]
    log(
        f"incidents: {len(incidents)} total, {len(in_aoi)} region-assigned, "
        f"{len(incidents) - len(in_aoi)} unplaced"
    )

    national, regional, snapshot = build_index.build(
        incidents=in_aoi,
        facilities=wiki_facilities,
        assets=assets,
        refinery_total_mtpa=refining_total,
        region_meta=region_meta,
        as_of=args.as_of,
        recovery_by_incident=recovery_by_incident,
    )

    enumerated = len(in_aoi)
    if coverage and coverage.get("reported_total_strikes"):
        coverage["enumerated_in_this_dataset"] = enumerated
        coverage["coverage_ratio"] = round(
            enumerated / coverage["reported_total_strikes"], 3
        )

    snapshot["coverage"] = coverage
    snapshot["parser_warnings"] = wiki_warnings
    snapshot["build_time"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")

    write_json(PROCESSED / "incidents.json", incidents)
    write_json(PROCESSED / "index_national.json", national)
    write_json(PROCESSED / "index_regional.json", {"dates": national["dates"], "regions": regional})
    write_json(PROCESSED / "snapshot.json", snapshot)
    write_json(PROCESSED / "refinery_inventory.json",
               {"refineries": refineries, "total_mtpa": round(refining_total, 1)})
    write_json(
        PROCESSED / "taxonomy.json",
        {
            "asset_classes": ASSET_CLASSES,
            "sectors": SECTORS,
            "causes": DISRUPTION_CAUSES,
            "analytic_concepts": ANALYTIC_CONCEPTS,
            "evidence_kinds": EVIDENCE_KINDS,
            "window_start": WINDOW_START,
        },
    )

    _mirror_to_web()

    log("-" * 62)
    log(f"ESDI {snapshot['esdi']}  sectors " +
        "  ".join(f"{k}={v}" for k, v in snapshot["sectors"].items()))
    if coverage:
        log(f"coverage: {enumerated} enumerated / "
            f"{coverage.get('reported_total_strikes')} reported")
    log("build complete")


def _mirror_to_web():
    WEB_DATA.mkdir(parents=True, exist_ok=True)
    copied = 0
    for path in PROCESSED.glob("*.json"):
        shutil.copy2(path, WEB_DATA / path.name)
        copied += 1
    for path in PROCESSED.glob("*.geojson"):
        shutil.copy2(path, WEB_DATA / path.name)
        copied += 1
    log(f"web: mirrored {copied} files to {WEB_DATA}")


if __name__ == "__main__":
    main()
