"""Build everything. `python -m pipeline.run`

Order matters: regions before assets (assets need the point-in-region index),
sources before the index, index before the web payload.

Output lands in data/processed/ and is mirrored into web/public/data/ so the Vite
build can serve it as static files. The database-shaped middle layer that a bigger
system would have is deliberately absent -- at this size, static JSON regenerated by
a scheduled job is the whole backend.
"""

import argparse
import collections
import datetime as dt
import shutil

from pipeline import build_assets, build_context, build_index
from pipeline.config import (
    ANALYTIC_CONCEPTS, ASSET_CLASSES, CURATED, DISRUPTION_CAUSES, EVIDENCE_KINDS,
    OPTIONAL_CONTEXT_FILES, PROCESSED, SCHEMA_VERSION, SECTOR_OF_CLASS, SECTORS,
    WEB_DATA, WINDOW_START,
)
from pipeline.fetch_refineries import build as build_refineries
from pipeline.fetch_wikipedia import build as build_wikipedia
from pipeline.recovery import load_recovery_records
from pipeline.util import fetch_json, log, read_csv, write_json

COVERAGE_PAGE = "2025%E2%80%932026_Russian_fuel_crisis"
COVERAGE_URL = "https://en.wikipedia.org/wiki/2025%E2%80%932026_Russian_fuel_crisis"


def load_curated_incidents():
    """Read the analyst-maintained incident file.

    This is the extension point for anything the automated parsers cannot reach:
    non-kinetic causes, electricity and gas events, and anything reported only in
    prose. Every row must carry at least one source URL.
    """
    path = CURATED / "incidents.csv"
    if not path.exists():
        return []
    out = []
    for row in read_csv(path):
        urls = [u for u in (row.get("source_urls") or "").split("|") if u]
        types = [t for t in (row.get("source_types") or "").split("|") if t]
        if not urls:
            log(f"  WARN curated incident {row.get('incident_id')} has no source URL; skipped")
            continue
        out.append(
            {
                "incident_id": row["incident_id"],
                # An episode is one disruption event; several incident rows may share an
                # episode_id when a source describes them as one strike. Defaults to the
                # incident's own id (each incident is its own episode).
                "episode_id": row.get("episode_id") or row["incident_id"],
                "asset_id": row.get("asset_id") or row["incident_id"],
                "asset_name": row.get("asset_name"),
                "linked_asset_id": row.get("linked_asset_id"),
                "asset_class": row.get("asset_class"),
                "region_code": row.get("region_code"),
                "date": row["date"],
                "date_start": row.get("date") ,
                "date_end": row.get("date_end"),
                "date_precision": row.get("date_precision") or "day",
                "cause": row.get("cause") or "unknown",
                "attribution": row.get("attribution") or "none",
                "attribution_confidence": row.get("attribution_confidence") or "not_applicable",
                "status": row.get("status") or "unknown",
                "confidence": row.get("confidence") or "possible",
                "capacity_affected_mw": _num(row.get("capacity_affected_mw")),
                "capacity_affected_mtpa": _num(row.get("capacity_affected_mtpa")),
                "capacity_affected_pct": _num(row.get("capacity_affected_pct")),
                # Transmission voltage class (kV) where a source states it — weights the
                # transmission event-burden. Not a capacity figure.
                "voltage_kv": _num(row.get("voltage_kv")),
                # Cost / economic scaffolding (iteration 1). Null unless a source gives a
                # figure. reported = a source stated it; estimated = an external estimate;
                # never a value the pipeline invents.
                "repair_cost_reported_usd_m": _num(row.get("repair_cost_reported_usd_m")),
                "repair_cost_estimate_low_usd_m": _num(row.get("repair_cost_estimate_low_usd_m")),
                "repair_cost_estimate_high_usd_m": _num(row.get("repair_cost_estimate_high_usd_m")),
                "cost_basis": row.get("cost_basis"),
                "conflicting_reports": (row.get("conflicting_reports") or "").lower() == "true",
                "notes": row.get("notes"),
                "first_seen": row.get("first_seen"),
                "last_verified": row.get("last_verified"),
                "sources": [
                    {"url": u, "publisher": None, "title": None,
                     "source_type": types[i] if i < len(types) else None}
                    for i, u in enumerate(urls)
                ],
                "origin": "curated",
            }
        )
    log(f"curated: {len(out)} incidents")
    return out


def load_asset_supplement(region_meta):
    """Curated infrastructure the automated feeds miss — currently AOI LNG terminals, which
    are absent from WRI (power plants) and OSM points as inventoried here (iteration 4, §11).

    Each row is placed at ADMIN-REGION precision: the asset sits at its region's
    representative centroid, marked precision="region", never a sourced facility coordinate.
    This fills the inventory gap that made the LNG layer a corpus-wide zero, without turning
    the map into a facility-level deck. Every row carries a public source. Gas-condensate
    complexes are NOT counted as LNG merely because an LNG producer owns them (§11)."""
    path = CURATED / "assets_supplement.csv"
    if not path.exists():
        return []
    out = []
    for row in read_csv(path):
        code = row.get("region_code")
        meta = region_meta.get(code)
        if not meta or not meta.get("centroid"):
            log(f"  WARN asset supplement: unknown region {code} for {row.get('asset_id')}")
            continue
        lon, lat = meta["centroid"]
        out.append({
            "asset_id": row["asset_id"],
            "name": row["name"],
            "asset_class": row["asset_class"],
            "fuel": None,
            "region_code": code,
            "capacity_mw": _num(row.get("capacity_mw")),
            "capacity_mtpa": _num(row.get("capacity_mtpa")),
            "commissioning_year": int(row["commissioning_year"]) if row.get("commissioning_year") else None,
            "owner": row.get("operator") or None,
            "status": row.get("status") or None,
            "lon": lon,
            "lat": lat,
            "precision": "region",
            "source": "Curated infrastructure supplement",
            "source_url": row.get("source_url") or None,
        })
    if out:
        by_class = collections.Counter(a["asset_class"] for a in out)
        log(f"asset supplement: {len(out)} curated assets ({dict(by_class)}), admin-region precision")
    return out


def load_region_context():
    """Population and other structural regional context (Rosstat census, etc.).

    STRUCTURAL context only -- population POTENTIALLY exposed, never population ACTUALLY
    affected. The two are kept strictly distinct; an observed civilian effect is only a
    sourced incident, never derived from population.
    """
    path = CURATED / "region_context.csv"
    if not path.exists():
        return {}
    out = {}
    for row in read_csv(path):
        code = row.get("region_code")
        if not code:
            continue
        out[code] = {
            "population_millions": _num(row.get("population_millions")),
            "population_source": row.get("source"),
        }
    log(f"region context: {len(out)} regions with structural data")
    return out


def load_crea_snapshots():
    """CREA monthly economic snapshots -- observed economic CONTEXT, monthly cadence.

    Deliberately NOT a strike feed and NEVER attributed to infrastructure disruption:
    export revenue moves for many reasons the data cannot separate. Versioned by
    reporting month + snapshot date, with provenance and revision status preserved.
    CREA publishes stable per-month public analysis pages (the source URLs); there is no
    documented machine-readable public API, so this is an analyst-maintained snapshot
    file per the design brief -- no API is fabricated.
    """
    path = CURATED / "crea_snapshots.csv"
    if not path.exists():
        return None
    by_metric = {}
    for row in read_csv(path):
        metric = row.get("metric")
        if not metric or not row.get("value"):
            continue
        by_metric.setdefault(metric, []).append({
            "reporting_month": row.get("reporting_month"),
            "snapshot_date": row.get("snapshot_date"),
            "value": _num(row.get("value")),
            "units": row.get("units"),
            "source_url": row.get("source_url"),
            "revision_status": row.get("revision_status"),
            "note": row.get("notes"),
        })
    for series in by_metric.values():
        series.sort(key=lambda x: x["reporting_month"] or "")
    total = sum(len(v) for v in by_metric.values())
    log(f"CREA: {total} monthly economic snapshots across {len(by_metric)} metrics")
    return {
        "provider": "Centre for Research on Energy and Clean Air (CREA)",
        "cadence": "monthly",
        "kind": "observed_economic_context",
        "caveat": (
            "Observed external economic indicators, monthly. NOT attributed to "
            "infrastructure strikes -- export revenue moves for many reasons this data "
            "cannot separate. CREA revises historical figures as shipment data is "
            "verified; reporting month and snapshot date are preserved."
        ),
        "metrics": by_metric,
    } if by_metric else None


def _num(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _facet_counts(assets, lines, incidents, snapshot):
    """Full-corpus counts per UI dimension, so the frontend never reverse-engineers the
    dataset to decide which controls exist (iteration 4, §18).

    Counts are deliberately SEPARATE by kind — a class can have infrastructure assets but
    zero incidents (LNG), or incidents but no inventoried asset (refineries live in the
    refinery inventory, not the asset layer). The taxonomy defines what the system
    understands; these counts are what the current corpus actually contains. A dimension a
    control derives its VISIBILITY from is the union of the relevant kinds:
      infrastructure class -> asset_class + line_class + incident_asset_class
      cause / confidence   -> incident counts
    Counters omit zero keys, which is exactly what a data-driven "hide the empty toggle"
    rule needs. Sector counts here are RECORD counts, never the (separate) sector score."""
    def count(values):
        c = collections.Counter(v for v in values if v)
        return dict(sorted(c.items(), key=lambda kv: (-kv[1], kv[0])))

    return {
        "asset_class": count(a["asset_class"] for a in assets),
        "line_class": count(f["properties"].get("asset_class") for f in lines),
        "incident_asset_class": count(i.get("asset_class") for i in incidents),
        "sector": count(SECTOR_OF_CLASS.get(i.get("asset_class")) for i in incidents),
        "cause": count(i.get("cause") for i in incidents),
        "confidence": count(i.get("confidence") for i in incidents),
        "recovery_state": count(d["recovery"]["recovery_status"] for d in snapshot["live_disruptions"]),
        "evidence_kind": dict(snapshot["recovery_stats"]["evidence_kind_counts"]),
    }


def load_coverage_benchmark():
    """Reported strike totals by war year, used to state our own coverage honestly.

    The source article tabulates how many strikes on Russian oil facilities have been
    reported in total. Comparing that with the number this dataset actually enumerates
    is the most useful single honesty statistic the dashboard can show.
    """
    from pipeline import wikitext as W

    url = (
        "https://en.wikipedia.org/w/api.php?action=parse&page="
        f"{COVERAGE_PAGE}&prop=wikitext&format=json&formatversion=2"
    )
    try:
        wt = fetch_json(url, "wiki_fuel_crisis.json", max_age_hours=24)["parse"]["wikitext"]
    except Exception as exc:  # noqa: BLE001 - benchmark is optional context
        log(f"  WARN coverage benchmark unavailable: {exc}")
        return None

    for table in W.find_tables(wt):
        headers, rows, spans = W.parse_table(table)
        head = [W.clean_cell(h).lower() for h in headers]
        if "cumulative" not in head:
            continue
        periods = []
        cumulative = None
        for row in rows:
            cells = [W.clean_cell(W.restore(c, spans)) for c in row]
            if len(cells) < 3:
                continue
            try:
                in_year = int(cells[-2].replace(",", ""))
                cum = int(cells[-1].replace(",", ""))
            except ValueError:
                continue
            periods.append({"period": cells[0], "strikes": in_year, "cumulative": cum})
            cumulative = cum
        if periods:
            return {
                "reported_total_strikes": cumulative,
                "by_period": periods,
                "source_url": COVERAGE_URL,
                "note": (
                    "Reported strikes on Russian oil facilities, as tabulated by the "
                    "source article. Used only to state this dataset's coverage; not "
                    "an input to any score."
                ),
            }
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--as-of", default=dt.date.today().isoformat())
    args = ap.parse_args()

    log("=" * 62)
    log(f"build starting, as_of={args.as_of}")
    log("=" * 62)

    assets, lines, region_meta = build_assets.build()
    assets += load_asset_supplement(region_meta)  # curated LNG etc., admin-region precision
    build_context.build()  # surrounding countries, borders, ocean — display only
    wiki_facilities, wiki_incidents, wiki_warnings = build_wikipedia()
    refineries, refining_total, refinery_reconciliation = build_refineries()
    curated = load_curated_incidents()
    coverage = load_coverage_benchmark()
    recovery_by_incident = load_recovery_records()
    region_context = load_region_context()
    crea = load_crea_snapshots()

    for inc in wiki_incidents:
        inc["origin"] = "wikipedia_strike_table"
        inc.setdefault("status", "unknown")

    incidents = wiki_incidents + curated
    incidents = [i for i in incidents if i["date"] >= WINDOW_START[:len(i["date"])]]
    incidents.sort(key=lambda i: i["date"])

    # Attach federal district to each region-assigned incident, for coverage analytics.
    district_of = {m["code"]: m["district"] for m in region_meta.values()}
    for inc in incidents:
        if inc.get("region_code"):
            inc["_district"] = district_of.get(inc["region_code"])

    in_aoi = [i for i in incidents if i.get("region_code")]
    log(
        f"incidents: {len(incidents)} total, {len(in_aoi)} region-assigned, "
        f"{len(incidents) - len(in_aoi)} unplaced"
    )

    # Transmission network context: HV-line count per region (transmission exposure is
    # event-burden, but the tracked network is shown as context in each region dossier).
    tx_lines_by_region = collections.Counter(
        f["properties"]["region_code"] for f in lines
        if f["properties"].get("asset_class") in ("transmission_line", "interconnector")
        and f["properties"].get("region_code")
    )

    national, regional, snapshot = build_index.build(
        incidents=in_aoi,
        facilities=wiki_facilities,
        assets=assets,
        refinery_total_mtpa=refining_total,
        region_meta=region_meta,
        as_of=args.as_of,
        recovery_by_incident=recovery_by_incident,
        transmission_lines_by_region=dict(tx_lines_by_region),
        region_context=region_context,
    )

    enumerated = len(in_aoi)
    if coverage and coverage.get("reported_total_strikes"):
        coverage["enumerated_in_this_dataset"] = enumerated
        coverage["coverage_ratio"] = round(
            enumerated / coverage["reported_total_strikes"], 3
        )

    snapshot["refinery_reconciliation"] = refinery_reconciliation
    snapshot["economic_context"] = crea
    snapshot["coverage"] = coverage
    snapshot["facet_counts"] = _facet_counts(assets, lines, incidents, snapshot)
    snapshot["parser_warnings"] = wiki_warnings
    snapshot["schema_version"] = SCHEMA_VERSION
    snapshot["build_time"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")

    write_json(PROCESSED / "assets.json", assets)
    write_json(PROCESSED / "incidents.json", incidents)
    write_json(PROCESSED / "index_national.json", national)
    write_json(PROCESSED / "index_regional.json", {"dates": national["dates"], "regions": regional})
    write_json(PROCESSED / "snapshot.json", snapshot)
    write_json(PROCESSED / "refinery_inventory.json",
               {"refineries": refineries, "total_mtpa": round(refining_total, 1),
                "reconciliation": refinery_reconciliation})
    write_json(
        PROCESSED / "taxonomy.json",
        {
            "asset_classes": ASSET_CLASSES,
            "sectors": SECTORS,
            "causes": DISRUPTION_CAUSES,
            "analytic_concepts": ANALYTIC_CONCEPTS,
            "evidence_kinds": EVIDENCE_KINDS,
            "window_start": WINDOW_START,
        },
    )

    # Data manifest (iteration 5): one stamp of the schema version and the files this
    # build emitted, so a client can distinguish app/data skew from a genuine outage and
    # tests can assert the contract. Written last, before the mirror copies it across.
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "build_time": snapshot["build_time"],
        "files": [
            {"name": p.name, "bytes": p.stat().st_size,
             "optional": p.name in OPTIONAL_CONTEXT_FILES}
            for p in sorted(PROCESSED.glob("*.json")) + sorted(PROCESSED.glob("*.geojson"))
            if p.name != "data_manifest.json"
        ],
    }
    write_json(PROCESSED / "data_manifest.json", manifest, indent=2)

    _mirror_to_web()

    log("-" * 62)
    log(f"ESDI {snapshot['esdi']}  sectors " +
        "  ".join(f"{k}={v}" for k, v in snapshot["sectors"].items()))
    if coverage:
        log(f"coverage: {enumerated} enumerated / "
            f"{coverage.get('reported_total_strikes')} reported")
    log("build complete")


def _mirror_to_web():
    WEB_DATA.mkdir(parents=True, exist_ok=True)
    copied = 0
    for path in PROCESSED.glob("*.json"):
        shutil.copy2(path, WEB_DATA / path.name)
        copied += 1
    for path in PROCESSED.glob("*.geojson"):
        shutil.copy2(path, WEB_DATA / path.name)
        copied += 1
    log(f"web: mirrored {copied} files to {WEB_DATA}")


if __name__ == "__main__":
    main()
