"""Build everything. `python -m pipeline.run`

Order matters: regions before assets (assets need the point-in-region index),
sources before the index, index before the web payload.

Output lands in data/processed/ and is mirrored into web/public/data/ so the Vite
build can serve it as static files. The database-shaped middle layer that a bigger
system would have is deliberately absent -- at this size, static JSON regenerated by
a scheduled job is the whole backend.
"""

import argparse
import collections
import datetime as dt
import shutil

from pipeline import build_assets, build_context, build_index, build_pipeline_network
from pipeline import fetch_osm, fetch_osm_pipelines
from pipeline.config import (
    ANALYTIC_CONCEPTS, ASSET_CLASSES, CURATED, DISRUPTION_CAUSES, EVIDENCE_KINDS,
    OPTIONAL_CONTEXT_FILES, PROCESSED, SCHEMA_VERSION, SECTOR_OF_CLASS, SECTORS,
    WEB_DATA, WINDOW_START,
)
from pipeline.fetch_refineries import build as build_refineries
from pipeline.fetch_wikipedia import build as build_wikipedia
from pipeline.recovery import load_recovery_records
from pipeline.util import fetch_json, log, read_csv, read_json, write_json

COVERAGE_PAGE = "2025%E2%80%932026_Russian_fuel_crisis"
COVERAGE_URL = "https://en.wikipedia.org/wiki/2025%E2%80%932026_Russian_fuel_crisis"


def load_curated_incidents():
    """Read the analyst-maintained incident file.

    This is the extension point for anything the automated parsers cannot reach:
    non-kinetic causes, electricity and gas events, and anything reported only in
    prose. Every row must carry at least one source URL.
    """
    path = CURATED / "incidents.csv"
    if not path.exists():
        return []
    out = []
    for row in read_csv(path):
        urls = [u for u in (row.get("source_urls") or "").split("|") if u]
        types = [t for t in (row.get("source_types") or "").split("|") if t]
        if not urls:
            log(f"  WARN curated incident {row.get('incident_id')} has no source URL; skipped")
            continue
        out.append(
            {
                "incident_id": row["incident_id"],
                # An episode is one disruption event; several incident rows may share an
                # episode_id when a source describes them as one strike. Defaults to the
                # incident's own id (each incident is its own episode).
                "episode_id": row.get("episode_id") or row["incident_id"],
                "asset_id": row.get("asset_id") or row["incident_id"],
                "asset_name": row.get("asset_name"),
                "linked_asset_id": row.get("linked_asset_id"),
                "asset_class": row.get("asset_class"),
                "region_code": row.get("region_code"),
                "date": row["date"],
                "date_start": row.get("date") ,
                "date_end": row.get("date_end"),
                "date_precision": row.get("date_precision") or "day",
                "cause": row.get("cause") or "unknown",
                "attribution": row.get("attribution") or "none",
                "attribution_confidence": row.get("attribution_confidence") or "not_applicable",
                "status": row.get("status") or "unknown",
                "confidence": row.get("confidence") or "possible",
                "capacity_affected_mw": _num(row.get("capacity_affected_mw")),
                "capacity_affected_mtpa": _num(row.get("capacity_affected_mtpa")),
                "capacity_affected_pct": _num(row.get("capacity_affected_pct")),
                # Transmission voltage class (kV) where a source states it — weights the
                # transmission event-burden. Not a capacity figure.
                "voltage_kv": _num(row.get("voltage_kv")),
                # Cost / economic scaffolding (iteration 1). Null unless a source gives a
                # figure. reported = a source stated it; estimated = an external estimate;
                # never a value the pipeline invents.
                "repair_cost_reported_usd_m": _num(row.get("repair_cost_reported_usd_m")),
                "repair_cost_estimate_low_usd_m": _num(row.get("repair_cost_estimate_low_usd_m")),
                "repair_cost_estimate_high_usd_m": _num(row.get("repair_cost_estimate_high_usd_m")),
                "cost_basis": row.get("cost_basis"),
                "conflicting_reports": (row.get("conflicting_reports") or "").lower() == "true",
                "notes": row.get("notes"),
                "first_seen": row.get("first_seen"),
                "last_verified": row.get("last_verified"),
                "sources": [
                    {"url": u, "publisher": None, "title": None,
                     "source_type": types[i] if i < len(types) else None}
                    for i, u in enumerate(urls)
                ],
                "origin": "curated",
            }
        )
    log(f"curated: {len(out)} incidents")
    return out


def load_asset_supplement(region_meta):
    """Curated infrastructure the automated feeds miss — currently AOI LNG terminals, which
    are absent from WRI (power plants) and OSM points as inventoried here (iteration 4, §11).

    Each row is placed at ADMIN-REGION precision: the asset sits at its region's
    representative centroid, marked precision="region", never a sourced facility coordinate.
    This fills the inventory gap that made the LNG layer a corpus-wide zero, without turning
    the map into a facility-level deck. Every row carries a public source. Gas-condensate
    complexes are NOT counted as LNG merely because an LNG producer owns them (§11)."""
    path = CURATED / "assets_supplement.csv"
    if not path.exists():
        return []
    out = []
    for row in read_csv(path):
        code = row.get("region_code")
        meta = region_meta.get(code)
        if not meta or not meta.get("centroid"):
            log(f"  WARN asset supplement: unknown region {code} for {row.get('asset_id')}")
            continue
        lon, lat = meta["centroid"]
        out.append({
            "asset_id": row["asset_id"],
            "name": row["name"],
            "asset_class": row["asset_class"],
            "fuel": None,
            "region_code": code,
            "capacity_mw": _num(row.get("capacity_mw")),
            "capacity_mtpa": _num(row.get("capacity_mtpa")),
            # Gas processing is metered in bcm/y raw gas, not MTPA — kept in an explicit field
            # (§16) so nothing parses a capacity out of prose at scoring time. Feeds ONLY the
            # experimental gas-processing sub-index, never the headline ESDI denominators.
            "capacity_bcm_y": _num(row.get("capacity_bcm_y")),
            "capacity_basis": row.get("capacity_basis") or None,
            "capacity_year": row.get("capacity_year") or None,
            "capacity_source": row.get("capacity_source") or None,
            "capacity_status": row.get("capacity_status") or None,
            "commissioning_year": int(row["commissioning_year"]) if row.get("commissioning_year") else None,
            "owner": row.get("operator") or None,
            "status": row.get("status") or None,
            "lon": lon,
            "lat": lat,
            "precision": "region",
            "scope": "analytic",
            "source": "Curated infrastructure supplement",
            "source_url": row.get("source_url") or None,
            "note": row.get("note") or None,
        })
    if out:
        by_class = collections.Counter(a["asset_class"] for a in out)
        log(f"asset supplement: {len(out)} curated assets ({dict(by_class)}), admin-region precision")
    return out


def load_region_context():
    """Population and other structural regional context (Rosstat census, etc.).

    STRUCTURAL context only -- population POTENTIALLY exposed, never population ACTUALLY
    affected. The two are kept strictly distinct; an observed civilian effect is only a
    sourced incident, never derived from population.
    """
    path = CURATED / "region_context.csv"
    if not path.exists():
        return {}
    out = {}
    for row in read_csv(path):
        code = row.get("region_code")
        if not code:
            continue
        out[code] = {
            "population_millions": _num(row.get("population_millions")),
            "population_source": row.get("source"),
        }
    log(f"region context: {len(out)} regions with structural data")
    return out


def load_crea_snapshots():
    """CREA monthly economic snapshots -- observed economic CONTEXT, monthly cadence.

    Deliberately NOT a strike feed and NEVER attributed to infrastructure disruption:
    export revenue moves for many reasons the data cannot separate. Versioned by
    reporting month + snapshot date, with provenance and revision status preserved.
    CREA publishes stable per-month public analysis pages (the source URLs); there is no
    documented machine-readable public API, so this is an analyst-maintained snapshot
    file per the design brief -- no API is fabricated.
    """
    path = CURATED / "crea_snapshots.csv"
    if not path.exists():
        return None
    by_metric = {}
    for row in read_csv(path):
        metric = row.get("metric")
        if not metric or not row.get("value"):
            continue
        by_metric.setdefault(metric, []).append({
            "reporting_month": row.get("reporting_month"),
            "snapshot_date": row.get("snapshot_date"),
            "value": _num(row.get("value")),
            "units": row.get("units"),
            "source_url": row.get("source_url"),
            "revision_status": row.get("revision_status"),
            "note": row.get("notes"),
        })
    for series in by_metric.values():
        series.sort(key=lambda x: x["reporting_month"] or "")
    total = sum(len(v) for v in by_metric.values())
    log(f"CREA: {total} monthly economic snapshots across {len(by_metric)} metrics")
    return {
        "provider": "Centre for Research on Energy and Clean Air (CREA)",
        "cadence": "monthly",
        "kind": "observed_economic_context",
        "caveat": (
            "Observed external economic indicators, monthly. NOT attributed to "
            "infrastructure strikes -- export revenue moves for many reasons this data "
            "cannot separate. CREA revises historical figures as shipment data is "
            "verified; reporting month and snapshot date are preserved."
        ),
        "metrics": by_metric,
    } if by_metric else None


def _num(value):
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


_EFFECT_KINDS = {"observed", "estimated", "modelled", "unknown"}


def load_effects(valid_incident_ids):
    """Curated, source-backed OBSERVED consequences of strikes (§25-28).

    Every row is a single sourced consequence with an evidence tag. Per-incident effects
    attach to their incident; rows with an empty incident_id are national/macro war-effort
    datapoints (strategic aggregates only). Region population is NEVER an effect here — a
    civilian effect is only ever a source that states people/customers actually affected.
    Repair costs are stored as amount+currency+year+source, never invented.
    """
    path = CURATED / "effects.csv"
    if not path.exists():
        return {"national": [], "by_incident": {}}
    national, by_incident = [], collections.defaultdict(list)
    orphaned = []
    for row in read_csv(path):
        kind = (row.get("evidence_kind") or "unknown").strip()
        if kind not in _EFFECT_KINDS:
            log(f"  WARN effects: unknown evidence_kind '{kind}' for {row.get('incident_id')}")
            kind = "unknown"
        rec = {
            "effect_type": (row.get("effect_type") or "").strip(),
            "evidence_kind": kind,
            "source_quality": (row.get("source_quality") or "").strip() or None,  # §31
            "value_numeric": _num(row.get("value_numeric")),
            "value_unit": row.get("value_unit") or None,
            "currency": row.get("currency") or None,
            "cost_year": row.get("cost_year") or None,
            "as_of_date": row.get("as_of_date") or None,
            "value_text": row.get("value_text") or None,
            "source_url": row.get("source_url") or None,
        }
        iid = (row.get("incident_id") or "").strip()
        if not iid:
            national.append(rec)
        elif iid in valid_incident_ids:
            by_incident[iid].append(rec)
        else:
            orphaned.append(iid)
    if orphaned:
        log(f"  WARN effects: {len(orphaned)} rows reference unknown incidents: {sorted(set(orphaned))}")
    log(f"effects: {sum(len(v) for v in by_incident.values())} per-incident + {len(national)} national")
    return {"national": national, "by_incident": dict(by_incident)}


def _facet_counts(assets, lines, incidents, snapshot, context_routes=None):
    """Full-corpus counts per UI dimension, so the frontend never reverse-engineers the
    dataset to decide which controls exist (iteration 4, §18).

    Counts are deliberately SEPARATE by kind — a class can have infrastructure assets but
    zero incidents (LNG), or incidents but no inventoried asset (refineries live in the
    refinery inventory, not the asset layer). The taxonomy defines what the system
    understands; these counts are what the current corpus actually contains. A dimension a
    control derives its VISIBILITY from is the union of the relevant kinds:
      infrastructure class -> asset_class + line_class + incident_asset_class
      cause / confidence   -> incident counts
    Counters omit zero keys, which is exactly what a data-driven "hide the empty toggle"
    rule needs. Sector counts here are RECORD counts, never the (separate) sector score."""
    def count(values):
        c = collections.Counter(v for v in values if v)
        return dict(sorted(c.items(), key=lambda kv: (-kv[1], kv[0])))

    return {
        "asset_class": count(a["asset_class"] for a in assets),
        # Analytic pipeline/grid lines only; context trunk routes are a SEPARATE count so a
        # continent of context routes can never imply thousands of disruption records (§15).
        "line_class": count(f["properties"].get("asset_class") for f in lines),
        "context_route_class": dict(sorted((context_routes or {}).items())),
        "incident_asset_class": count(i.get("asset_class") for i in incidents),
        "sector": count(SECTOR_OF_CLASS.get(i.get("asset_class")) for i in incidents),
        "cause": count(i.get("cause") for i in incidents),
        "confidence": count(i.get("confidence") for i in incidents),
        "recovery_state": count(d["recovery"]["recovery_status"] for d in snapshot["live_disruptions"]),
        "evidence_kind": dict(snapshot["recovery_stats"]["evidence_kind_counts"]),
    }


def load_coverage_benchmark():
    """Reported strike totals by war year, used to state our own coverage honestly.

    The source article tabulates how many strikes on Russian oil facilities have been
    reported in total. Comparing that with the number this dataset actually enumerates
    is the most useful single honesty statistic the dashboard can show.
    """
    from pipeline import wikitext as W

    url = (
        "https://en.wikipedia.org/w/api.php?action=parse&page="
        f"{COVERAGE_PAGE}&prop=wikitext&format=json&formatversion=2"
    )
    try:
        wt = fetch_json(url, "wiki_fuel_crisis.json", max_age_hours=24)["parse"]["wikitext"]
    except Exception as exc:  # noqa: BLE001 - benchmark is optional context
        log(f"  WARN coverage benchmark unavailable: {exc}")
        return None

    for table in W.find_tables(wt):
        headers, rows, spans = W.parse_table(table)
        head = [W.clean_cell(h).lower() for h in headers]
        if "cumulative" not in head:
            continue
        periods = []
        cumulative = None
        for row in rows:
            cells = [W.clean_cell(W.restore(c, spans)) for c in row]
            if len(cells) < 3:
                continue
            try:
                in_year = int(cells[-2].replace(",", ""))
                cum = int(cells[-1].replace(",", ""))
            except ValueError:
                continue
            periods.append({"period": cells[0], "strikes": in_year, "cumulative": cum})
            cumulative = cum
        if periods:
            return {
                "reported_total_strikes": cumulative,
                "by_period": periods,
                "source_url": COVERAGE_URL,
                "note": (
                    "Reported strikes on Russian oil facilities, as tabulated by the "
                    "source article. Used only to state this dataset's coverage; not "
                    "an input to any score."
                ),
            }
    return None


# The oil-strike benchmark (the Wikipedia "reported strikes on Russian oil facilities" total)
# describes ONE universe: kinetic attacks on oil facilities. Coverage against it must use a
# matching numerator, or it mixes universes (iteration 6 correction, §3-§5).
OIL_SECTORS = {"refining", "oil_logistics"}
STRIKE_CAUSES = {"kinetic_strike", "sabotage"}
_DISCOVERY_SOURCES = {
    "refining": "Wikipedia strike table + curated OSINT",
    "oil_logistics": "Wikipedia strike table + curated OSINT",
    "electric_generation": "curated OSINT (Reuters/Astra/regional governors)",
    "transmission": "curated OSINT (Reuters/Astra/regional governors)",
    "gas": "curated OSINT + operator/industry inventory",
    "coal": "operator/industry inventory (no disruption events found)",
}


def _build_coverage(in_aoi, benchmark, snapshot):
    """Return (oil_benchmark, sector_matrix). Coverage is three DIFFERENT concepts kept
    separate (§5): EVENT coverage (only the oil sectors have a defensible benchmark),
    ASSET-INVENTORY coverage, and RECOVERY-EVIDENCE coverage. Non-oil sectors get an honest
    descriptive state, never a fabricated completeness percentage."""
    sec_of = lambda i: SECTOR_OF_CLASS.get(i.get("asset_class"))
    events_by_sector = collections.Counter(sec_of(i) for i in in_aoi)
    # numerator that matches the oil-facility strike benchmark universe
    oil_strikes = sum(1 for i in in_aoi
                      if sec_of(i) in OIL_SECTORS and i.get("cause") in STRIKE_CAUSES)

    oil_benchmark = None
    if benchmark and benchmark.get("reported_total_strikes"):
        total = benchmark["reported_total_strikes"]
        oil_benchmark = {
            "reported_oil_strikes": total,
            "enumerated_oil_strikes": oil_strikes,
            "coverage_ratio": round(oil_strikes / total, 3),
            "total_events_all_sectors": len(in_aoi),
            "numerator_definition": (
                "kinetic strikes and sabotage on refining and oil-logistics facilities in the "
                "AOI — the same universe the benchmark counts"
            ),
            "benchmark_source": benchmark.get("source_url"),
            "benchmark_categories": "reported strikes on Russian oil facilities",
            "by_period": benchmark.get("by_period"),
            "note": (
                "Benchmark-aligned coverage: numerator and denominator are the SAME oil-strike "
                "universe. Iterations 1-5 divided ALL energy events by this oil-only benchmark, "
                "which mixed universes and overstated coverage; that is corrected here."
            ),
        }

    rs_by_sector = snapshot["recovery_stats"]["by_sector"]
    asset_fc = snapshot["facet_counts"]["asset_class"]
    classes_of = collections.defaultdict(list)
    for cls, sec in SECTOR_OF_CLASS.items():
        classes_of[sec].append(cls)

    matrix = {}
    for sec in SECTORS:
        rs = rs_by_sector.get(sec, {})
        n = events_by_sector.get(sec, 0)
        entry = {
            "event_count": n,
            "discovery_sources": _DISCOVERY_SOURCES.get(sec, "curated"),
            "has_event_benchmark": sec in OIL_SECTORS,
            "asset_inventory_count": sum(asset_fc.get(c, 0) for c in classes_of.get(sec, [])),
            # RECOVERY-EVIDENCE coverage (§5): ANY recovery evidence for the sector, not just
            # observed full-restoration durations — a partial restart is still evidence. So a
            # class (e.g. transmission) can show recovery evidence while having no observed
            # median. The Recovery tab keeps observed vs partial distinct.
            "recovery_episodes": (rs.get("observed_restoration_episodes", 0)
                                  + rs.get("partial_restart_episodes", 0)),
            "recovery_observed_episodes": rs.get("observed_restoration_episodes", 0),
            "disrupted_facilities": rs.get("disrupted_facilities", 0),
            "last_audit": snapshot["as_of"],
        }
        if sec in OIL_SECTORS:
            entry["event_coverage_state"] = "oil-strike benchmark (shared, oil-sector level)"
        else:
            entry["event_coverage_state"] = (
                "no events" if n == 0 else "thin" if n < 5 else "expanded but unbenchmarked"
            )
        matrix[sec] = entry
    return oil_benchmark, matrix


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--as-of", default=dt.date.today().isoformat())
    args = ap.parse_args()

    log("=" * 62)
    log(f"build starting, as_of={args.as_of}")
    log("=" * 62)

    assets, lines, region_meta = build_assets.build()
    assets += load_asset_supplement(region_meta)  # curated LNG etc., admin-region precision
    build_context.build()  # surrounding countries, borders, ocean, rivers — display only
    # Continental oil/gas trunk CONTEXT network: a SEPARATE path, scope=context, never scored.
    #
    # Iteration 9 replaced the way-at-a-time builder with relation-aware reconstruction. The old
    # one asked "is this OSM way 50 km long?" of each fragment of a trunk line and deleted
    # anything the analytic feed also carried, which cost 161,899 km of route geometry and hid
    # the Russian backbone whenever the analytic layer was off (docs/PIPELINE_GAP_AUDIT.md).
    # Overlap with the analytic feed is now MARKED, not removed — the context layer has to stand
    # on its own because its toggle is independent in the UI.
    analytic_osm_ids = {f["properties"].get("osm_id") for f in lines if f["properties"].get("osm_id")}
    osm_pipes = fetch_osm_pipelines.fetch_all()
    # Named trunk ways that belong to no relation still deserve a route. Re-reading the analytic
    # OSM fetch is free (it is served from the same on-disk cache build_assets just used).
    osm_ways = fetch_osm.fetch_all()
    ctx_net = build_pipeline_network.build(
        relations=osm_pipes["relations"],
        member_tags=osm_pipes["member_tags"],
        way_elements=osm_ways.get("pipeline_gas", []) + osm_ways.get("pipeline_oil", []),
        analytic_osm_ids=analytic_osm_ids,
    )
    wiki_facilities, wiki_incidents, wiki_warnings = build_wikipedia()
    refineries, refining_total, refinery_reconciliation = build_refineries()
    curated = load_curated_incidents()
    coverage = load_coverage_benchmark()
    recovery_by_incident = load_recovery_records()
    region_context = load_region_context()
    crea = load_crea_snapshots()

    for inc in wiki_incidents:
        inc["origin"] = "wikipedia_strike_table"
        inc.setdefault("status", "unknown")

    incidents = wiki_incidents + curated
    incidents = [i for i in incidents if i["date"] >= WINDOW_START[:len(i["date"])]]
    incidents.sort(key=lambda i: i["date"])

    # Attach federal district to each region-assigned incident, for coverage analytics.
    district_of = {m["code"]: m["district"] for m in region_meta.values()}
    for inc in incidents:
        if inc.get("region_code"):
            inc["_district"] = district_of.get(inc["region_code"])

    in_aoi = [i for i in incidents if i.get("region_code")]
    log(
        f"incidents: {len(incidents)} total, {len(in_aoi)} region-assigned, "
        f"{len(incidents) - len(in_aoi)} unplaced"
    )

    # Transmission network context: HV-line count per region (the transmission BURDEN is an
    # event-burden proxy, not a capacity share; the tracked network is shown as context only).
    tx_lines_by_region = collections.Counter(
        f["properties"]["region_code"] for f in lines
        if f["properties"].get("asset_class") in ("transmission_line", "interconnector")
        and f["properties"].get("region_code")
    )

    national, regional, snapshot = build_index.build(
        incidents=in_aoi,
        facilities=wiki_facilities,
        assets=assets,
        refinery_total_mtpa=refining_total,
        region_meta=region_meta,
        as_of=args.as_of,
        recovery_by_incident=recovery_by_incident,
        transmission_lines_by_region=dict(tx_lines_by_region),
        region_context=region_context,
    )

    # Canonical refinery linkage completeness (§9) — identity/linkage, NOT disruption coverage.
    from pipeline import refinery_registry as _RR
    denom_cap = {r["canonical_id"]: r["capacity_mtpa"] for r in refineries
                 if r.get("denominator_status") != "exclude" and r.get("canonical_id") and r.get("capacity_mtpa")}
    struck, unresolved = set(), []
    for i in (x for x in in_aoi if x.get("asset_class") == "refinery"):
        cid = _RR.resolve(i.get("asset_id")) or _RR.resolve(i.get("asset_name"))
        if cid and cid in denom_cap:
            struck.add(cid)
        elif cid is None:
            unresolved.append(i.get("asset_name"))
    total_denom_cap = round(sum(denom_cap.values()), 1) or 1
    refinery_reconciliation["canonical_linkage"] = {
        "denominator_refineries": len(denom_cap),
        "struck_refineries": len(struck),
        "mtpa_struck": round(sum(denom_cap.get(c, 0) for c in struck), 1),
        "pct_denominator_mtpa_struck": round(100 * sum(denom_cap.get(c, 0) for c in struck) / total_denom_cap, 1),
        "incidents_unresolved_to_registry": sorted({x for x in unresolved if x}),
        "note": ("Identity/linkage completeness, NOT disruption coverage: how much of the tracked "
                 "denominator resolves to a struck canonical refinery. Naftan (Belarus) is "
                 "intentionally outside the Russian denominator."),
    }
    snapshot["refinery_reconciliation"] = refinery_reconciliation
    snapshot["economic_context"] = crea
    # Source-backed observed effects (§25-28), keyed to incidents in the AOI universe.
    snapshot["strategic_effects"] = load_effects({i["incident_id"] for i in in_aoi})
    snapshot["facet_counts"] = _facet_counts(assets, lines, incidents, snapshot, ctx_net)

    # Network SOURCE COVERAGE (iteration 9, §21). Deliberately in the snapshot rather than a
    # separate fetch: it is small, and it belongs next to the other "how good is the evidence"
    # metadata. This describes how completely the CONTEXT network is sourced — it is not a
    # disruption measure and never enters ESDI.
    quality_path = PROCESSED / "pipeline_network_quality.json"
    if quality_path.exists():
        snapshot["network_coverage"] = read_json(quality_path)

    # Coverage is computed AFTER facet_counts/recovery_stats exist — the matrix reads them.
    oil_benchmark, coverage_matrix = _build_coverage(in_aoi, coverage, snapshot)
    if coverage and oil_benchmark:
        # Correct the legacy top-level fields to the OIL-STRIKE universe (§4). enumerated now
        # counts oil-sector strikes, not all energy events, so the ratio matches the benchmark.
        coverage["enumerated_in_this_dataset"] = oil_benchmark["enumerated_oil_strikes"]
        coverage["coverage_ratio"] = oil_benchmark["coverage_ratio"]
        coverage["total_events_all_sectors"] = len(in_aoi)
        coverage["numerator_definition"] = oil_benchmark["numerator_definition"]
        coverage["note"] = oil_benchmark["note"]
        coverage["oil_benchmark"] = oil_benchmark
    snapshot["coverage"] = coverage
    snapshot["coverage_matrix"] = coverage_matrix
    snapshot["parser_warnings"] = wiki_warnings
    snapshot["schema_version"] = SCHEMA_VERSION
    snapshot["build_time"] = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")

    write_json(PROCESSED / "assets.json", assets)
    write_json(PROCESSED / "incidents.json", incidents)
    write_json(PROCESSED / "index_national.json", national)
    write_json(PROCESSED / "index_regional.json", {"dates": national["dates"], "regions": regional})
    write_json(PROCESSED / "snapshot.json", snapshot)
    write_json(PROCESSED / "refinery_inventory.json",
               {"refineries": refineries, "total_mtpa": round(refining_total, 1),
                "reconciliation": refinery_reconciliation})
    write_json(
        PROCESSED / "taxonomy.json",
        {
            "asset_classes": ASSET_CLASSES,
            "sectors": SECTORS,
            "causes": DISRUPTION_CAUSES,
            "analytic_concepts": ANALYTIC_CONCEPTS,
            "evidence_kinds": EVIDENCE_KINDS,
            "window_start": WINDOW_START,
        },
    )

    # Data manifest (iteration 5): one stamp of the schema version and the files this
    # build emitted, so a client can distinguish app/data skew from a genuine outage and
    # tests can assert the contract. Written last, before the mirror copies it across.
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "build_time": snapshot["build_time"],
        "files": [
            {"name": p.name, "bytes": p.stat().st_size,
             "optional": p.name in OPTIONAL_CONTEXT_FILES}
            for p in sorted(PROCESSED.glob("*.json")) + sorted(PROCESSED.glob("*.geojson"))
            if p.name != "data_manifest.json"
        ],
    }
    write_json(PROCESSED / "data_manifest.json", manifest, indent=2)

    _mirror_to_web()

    # Single source of truth for headline numbers (§2) — regenerated every build so no doc
    # drifts. A test asserts it matches the snapshot.
    from pipeline import current_state
    current_state.write(snapshot)

    log("-" * 62)
    log(f"ESDI {snapshot['esdi']}  sectors " +
        "  ".join(f"{k}={v}" for k, v in snapshot["sectors"].items()))
    if coverage and oil_benchmark:
        log(f"coverage: {oil_benchmark['enumerated_oil_strikes']} oil-strikes enumerated / "
            f"{oil_benchmark['reported_oil_strikes']} reported oil strikes "
            f"({len(in_aoi)} total events across all sectors)")
    log("build complete")


def _mirror_to_web():
    """Copy the processed payload into the web bundle, and PRUNE what the pipeline no longer
    produces. Without the prune, a file that stops being generated lingers in `web/public/data`
    and ships forever — 1.28 MB of GEM records did exactly that, deployed and never loaded."""
    WEB_DATA.mkdir(parents=True, exist_ok=True)
    produced = {p.name for p in PROCESSED.glob("*.json")} | {p.name for p in PROCESSED.glob("*.geojson")}
    stale = [p for p in WEB_DATA.iterdir()
             if p.suffix in (".json", ".geojson") and p.name not in produced]
    for p in stale:
        p.unlink()
        log(f"web: pruned stale {p.name}")
    copied = 0
    for path in PROCESSED.glob("*.json"):
        shutil.copy2(path, WEB_DATA / path.name)
        copied += 1
    for path in PROCESSED.glob("*.geojson"):
        shutil.copy2(path, WEB_DATA / path.name)
        copied += 1
    log(f"web: mirrored {copied} files to {WEB_DATA}")


if __name__ == "__main__":
    main()
